


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme-provider";
import { DataProvider } from "@/context/dataContext";
import NavbarMenu from "@/components/ui/navbar-menu"; // Add this import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
<<<<<<< HEAD
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
=======
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
>>>>>>> 48f4abe57722afc2cb29937fa2e1ace87eff017b
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavbarMenu /> {/* Navbar at the top */}
          <DataProvider>{children}</DataProvider>
          <Toaster expand={true} richColors closeButton={true} />
        </ThemeProvider>
      </body>
    </html>
  );
}






